### ISSUE TITLE
xarray .sel 'dimensions or multi-index levels ['time'] do not exist' aggravation issue

### ISSUE THREAD

**Issue by robfatland** [pangeo-data/pangeo_ocean_examples#15]
Issue: I don't know why a straightforward .sel() operation is throwing the error shown in the Subject.

Meta-Issue: I don't know how a person with my problem would go about learning / finding the solution to this problem; really a time-lost-plus-aggravation issue for the noob. I am that noob. 

I am placing this in pangeo_ocean_examples because it happens to be ocean data; but really it is a general problem. Here we go: 

I have a profiler rising and falling through the water column nine times per day; and two of those profiles (noon, midnight) activate a nitrate sensor. This has its own clock; therefore its own timestamps; and the two profiles generate 429 values in total. So far so good. 

The profiler runs a CTD which produces almost the full 86,400 daily observations: On its own separate clock.

Therefore I have two xxx.nc files i.e. two xarray Datasets: One with 429 nitrate values and the other with 86,397 CTD observations. 

In both cases the xarray Dataset dimension is 'obs' (an integer index) where 'time' is a coordinate tied to the obs dimension. 

The goal is to match get the depths corresponding to the nitrate measurements across these independent clocks by means of `.sel(time=..., method='nearest')`.The error I see is discussed in the xarray Issues and etcetera but I can't discern a good solution.

Let's suppose I bring together a depth DataArray (86397 values) and a nitrate DataArray (429 values) in a single xr.Dataset called `d`. I give the depth a dimension/coordinate `time` and I give the nitrate data a dimension/coordinate `time1`. Here is the output of `print(d)`:

```
<xarray.Dataset>
Dimensions:  (time: 86397, time1: 429)
Coordinates:
  * time     (time) datetime64[ns] 2017-08-21T00:00:00.803386368 ... 2017-08-21T23:59:59.015734272
  * time1    (time1) datetime64[ns] 2017-08-21T07:22:21.166164480 ... 2017-08-21T21:46:56.991324672
Data variables:
    depth    (time) float64 190.3 190.3 190.3 190.3 ... 190.5 190.5 190.5 190.5
    nitrate  (time1) float64 30.41 30.44 30.55 30.37 ... 0.6578 0.7092 0.6619
```
Here is the attempt to create a new DataArray `da` using `.sel()`
```
time_selector=d.time1.values.tolist()
da=d['nitrate'].sel(time=time_selector, method='nearest')
```
and this produces the Value Error as given in the Issue subject; and in full detail below. 

Q1: What is going on here? 
Bonus Q2: How does one learn `xarray` so as to not run aground in this manner? 

Full error msg follows...

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-215-2cb483f8a1ab> in <module>()
----> 1 da=d['nitrate'].sel(time=time_selector, method='nearest')

/opt/conda/lib/python3.6/site-packages/xarray/core/dataarray.py in sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
    845         ds = self._to_temp_dataset().sel(
    846             indexers=indexers, drop=drop, method=method, tolerance=tolerance,
--> 847             **indexers_kwargs)
    848         return self._from_temp_dataset(ds)
    849 

/opt/conda/lib/python3.6/site-packages/xarray/core/dataset.py in sel(self, indexers, method, tolerance, drop, **indexers_kwargs)
   1619         indexers = either_dict_or_kwargs(indexers, indexers_kwargs, 'sel')
   1620         pos_indexers, new_indexes = remap_label_indexers(
-> 1621             self, indexers=indexers, method=method, tolerance=tolerance)
   1622         result = self.isel(indexers=pos_indexers, drop=drop)
   1623         return result._replace_indexes(new_indexes)

/opt/conda/lib/python3.6/site-packages/xarray/core/coordinates.py in remap_label_indexers(obj, indexers, method, tolerance, **indexers_kwargs)
    353 
    354     pos_indexers, new_indexes = indexing.remap_label_indexers(
--> 355         obj, v_indexers, method=method, tolerance=tolerance
    356     )
    357     # attach indexer's coordinate to pos_indexers

/opt/conda/lib/python3.6/site-packages/xarray/core/indexing.py in remap_label_indexers(data_obj, indexers, method, tolerance)
    235     new_indexes = {}
    236 
--> 237     dim_indexers = get_dim_indexers(data_obj, indexers)
    238     for dim, label in iteritems(dim_indexers):
    239         try:

/opt/conda/lib/python3.6/site-packages/xarray/core/indexing.py in get_dim_indexers(data_obj, indexers)
    203     if invalid:
    204         raise ValueError("dimensions or multi-index levels %r do not exist"
--> 205                          % invalid)
    206 
    207     level_indexers = defaultdict(dict)

ValueError: dimensions or multi-index levels ['time'] do not exist
```

**Comment by rabernat** [comment]
I'm reluctant for this repo to become a general place for questions about all aspects of oceanographic data analysis, but for you Rob I'll make an exception. 😉 Your meta-point is a good one of course and I'll address it at the end.

In terms of your actual problem, I think you explain it very clearly. The error seems pretty useful to me. It is telling us that `time` is not a dimension of `nitrate`; its dimension is `time1`, which is clear from the printed output
```
Data variables:
    depth    (time) 
    nitrate  (time1)
```
It would have been more useful if the error message also said, "possible dimensions are: time1". I believe your example would work if you done 
```python
da=d.nitrate.sel(time1=d.time.values, method='nearest')
```
However, I can't verify that for sure.

 More generally, it sounds like you want to _interpolate_ time1 to time2? If so, I would use xarray's relatively new `interp` function: http://xarray.pydata.org/en/stable/interpolation.html.
```python
da=d.nitrate.interp(time1=d.time.values)
```
But I haven't actually tried this and can't promise it works either.

My first reaction was that this sort of question belongs on Stack Overflow or the xarray issue tracker. The advantage of these is that they produce some kind of permanent, searchable public record. But online discussions often break down because the next step is often either a) you try to share your data with me or b) someone asks you convert your actual problem into a copy-pasteable simplified example with synthetic data. Neither of those is very easy or welcoming to a n00b. 

With Pangeo it seems like we have the opportunity to solve this techincal problem because we can potentially both have access to the exact same environment and the exact same data, via the cloud. So you could cut and paste your actual code from your environment and I could just run it immediately. What if we had a chat window right in a jupyterlab on a shared cluster, where people could just post questions and talk about data and code?

The much harder question you are getting at is, whose job is it to provide general education about how to use pangeo-related tools? I wish one of our existing grants had a position explicitly dedicated to community tech support, outreach, and education. But we don't. I find @mrocklin's blog post [Public Institutions and Open Source Software](http://matthewrocklin.com/blog/work/2018/08/21/institutional-open-source) pretty insightful on this topic. Institutions like NCAR, and to some extent big universities departments like UW, Columbia, etc, already put a lot of effort into supporting their own tools (like NCL, etc.) But nobody "owns" xarray, so nobody sees it as their mandate to educate people about it. It has just spread organically, and unevenly. If NCAR and similar places could pivot from exclusively supporting their own in-house tools to supporting an open source ecosystem more broadly, that would be good for everyone.

**Comment by robfatland** [comment]
Ryan thanks a ton; for the basics and the pointer to `.interp()`. I agree this belongs elsewhere so let me suggest a few steps here and then address the elephant.

- I'll Close this and feel free to just delete the issue (I'll open new ones elsewhere)
- My tactical issue is now resolved so I can continue building this notebook
- The good news is that I basically understood what was going on but was making a 'dumb mistake' rather than me having a major misconception; a relief
- As I'm writing both content-focused notebooks and Notebooks for n00bs I will capture this exchange in the latter in streamlined form if you don't object.

In these n00b notebooks I'm taking time to be fairly gradual and methodical. I think Python packages like xarray can obscure their own functionality for very good aesthetic reasons. An xarray Dataset has 110 attributes before you put any data in it. For me that has resulted in a very frustrating experience so maybe we agree on 'general education needed'.

Also: Here is a gratuitous fling about the problem with stack overflow: What it teaches me is how to craft a carefully worded search string to find a matching issue, hoping for the line of code in the green checkbox reply that gets me on my way. This procedure is necessarily not connected with my context web (except incidentally) which is completely the opposite of how people learn (according to the NRC's excellent book _How People Learn_ for example.) As a result my context web becomes a collection of magical spells. And don't get me wrong: I love stack overflow and use it all the time; but I should probably start generating issues there.

Anyway I also agree pangeo provides a rising tide opportunity on the cloud; let's maybe keep that conversation going. thanks again

**Comment by robfatland** [comment]
oh, and closing Issue

**Comment by hafez-ahmad** [comment]
ds2=ds.sel(time=slice('2016-10-26 04:45:00'))
Traceback (most recent call last):

  File "<ipython-input-95-f4a635e775ff>", line 1, in <module>
    ds2=ds.sel(time=slice('2016-10-26 04:45:00'))

  File "C:\Users\hafez\anaconda3\lib\site-packages\xarray\core\dataset.py", line 2066, in sel
    self, indexers=indexers, method=method, tolerance=tolerance

  File "C:\Users\hafez\anaconda3\lib\site-packages\xarray\core\coordinates.py", line 397, in remap_label_indexers
    obj, v_indexers, method=method, tolerance=tolerance

  File "C:\Users\hafez\anaconda3\lib\site-packages\xarray\core\indexing.py", line 254, in remap_label_indexers
    dim_indexers = get_dim_indexers(data_obj, indexers)

  File "C:\Users\hafez\anaconda3\lib\site-packages\xarray\core\indexing.py", line 220, in get_dim_indexers
    raise ValueError(f"dimensions or multi-index levels {invalid!r} do not exist")

ValueError: dimensions or multi-index levels ['time'] do not exist
