### ISSUE TITLE
dask server extension is not working

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo_ocean_examples#16]
I can't start dask servers from the binder jupyterlab. 

I would love some help debugging in fixing this quickly. maybe @scottyhq can help?

**Comment by scottyhq** [comment]
hmmm. so it looks like you haven't rebuilt this image in the last 26 days, correct? in which case i guess it's due to a recent change to the kubernetes cluster? 

@jhamman - the only change i can think of is with the nodegroup labels/taints: https://github.com/pangeo-data/pangeo-cloud-federation/issues/264 

related:
https://github.com/pangeo-data/pangeo-stacks/issues/48

for now, launching from a notebook cell instead of from the dashboard is working:
```python
import dask
from dask_kubernetes import KubeCluster
from dask.distributed import Client
from dask.distributed import wait, progress
cluster = KubeCluster(n_workers=2)
cluster
```

**Comment by jhamman** [comment]
This binder is using dask-k8s 0.7 (before the latest release) so none of the scheduling changes should apply. 

@rabernat - are you trying to use the dask-labextension? ASFAIK, this is not working with dask-k8s under any configuration right now.

**Comment by rabernat** [comment]
Thanks for the replies guys.

> are you trying to use the dask-labextension to launch your cluster?

Yes

> ASFAIK, this is not working with dask-k8s under any configuration right now.

It's working on ocean.pangeo.io right now. I just want the same thing on binder. Is that not possible?

**Comment by ian-r-rose** [comment]
@rabernat So far as I know this should be working (and is, on ocean.pangeo.io and nasa.pangeo.io).

**Comment by scottyhq** [comment]
The dask extension on this older binder image is also still working currently:
https://github.com/scottyhq/esip-tech-dive

**Comment by rabernat** [comment]
This binder is just using the standard pangeo notebook:

https://github.com/pangeo-data/pangeo_ocean_examples/blob/b2fe7f130480428166cf3f414db40a4e03a0f21f/binder/Dockerfile#L1-L12

I guess I need some extra secret sauce to make the labextension work. Would this `postBuild` from ocean (using the same base image) also work here?

https://github.com/pangeo-data/pangeo-cloud-federation/blob/a5900ec7fb2d254504fed6d164a3f1a0a036e427/deployments/ocean/image/binder/postBuild#L1-L6

**Comment by scottyhq** [comment]
@rabernat - i don't think the config is the issue here, it is that your binder pangeo-notebook has dask-labextension 0.3.3. whereas your ocean image pins 0.3.1 (https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/ocean/image/binder/environment.yml#L6)

@ian-r-rose and @mrocklin if I understand correctly, dask-labextension>0.3.1 is not going to work with dask-kubernetes currently (https://github.com/pangeo-data/pangeo-stacks/issues/48#issuecomment-494599317)

**Comment by mrocklin** [comment]
You can't happily use it to control clusters.  You should still be able to use the dashboard buttons though.

**Comment by daxsoule** [comment]
Any progress on this issue? Dask still will not launch from this binder. Is there a work around? I am working with a group of educators this week for which I think this demo would be particularly useful.

**Comment by rabernat** [comment]
@daxsoule - the solution is to update the binder's configuration to  point to dask-labextension 0.3.1. There are several ways to accomplish this, but I haven't had time myself to do it. I would welcome a pull request from you or anyone else who wants to try to debug it.

What should probably be done is to update this image to use the new [onbuild](https://github.com/pangeo-data/pangeo-stacks/#customize-images-with-the--onbuild-variants) functionality from pangeo-stacks. (Has this successfully been done with a binder yet?)

@scottyhq is the resident expert on this stuff and can perhaps advise.

**Comment by daxsoule** [comment]
?Thanks Ryan!


Sorry I never made the pull request. I have been traveling and my hope was to work on that next week when I got back home. Thanks for making the fix and for all the other help.


Best,


Dax


Dax Soule

School of Earth and Environmental Sciences

Queens College

Flushing, NY 11367

(718) 997-3329

________________________________
